name: demo1
version: 3.5.0


dependencies:
  shared_preferences: ^2.5.3
  fcontrol_nullsafety: 2.0.0
  dio: 5.9.0
  extended_image: any
  hive_ce_flutter: any
  fbroadcast_nullsafety: 4.0.6
  loading_more_list_fast: ^7.3.0
  loading_more_list_library_fast: ^4.3.0
  dd_js_util:
    git:
      url: https://github.com/mdddj/dd_js_util
      ref: 7.1.1-oh
  simple_ui_theme: any
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  hooks_riverpod: any
  fbutton_nullsafety: 5.0.0
  crypto: ^3.0.7
  encrypt: 5.0.3
  waterfall_flow: 3.1.1
  html: 0.15.6
  palette_generator: 0.3.3+7
  flex_color_scheme: ^8.3.1
  loading_animation_widget: 1.3.0
  fsuper_nullsafety: 3.0.3
  connectivity_plus: any
  connectivity_plus_ohos: ^0.0.3
  shimmer: 3.0.0
  flutter_slidable: ^4.0.3
  image_picker: ^1.2.0
  show_up_animation: 2.1.2
  pull_to_refresh_notification: 3.1.1
  bubble_tab_indicator: 0.1.6
  flutter_swiper_null_safety_flutter3: 4.0.3
  flutter_widget_from_html_core: any
  webview_flutter: 4.13.0
  async: ^2.13.0
  responsive_builder: 0.7.1
  cupertino_icons: ^1.0.8
  common_utils: 2.1.0
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  freezed_annotation: 3.1.0
  permission_handler: any
  get_it: any
  package_info_plus: any
  blurrycontainer: 2.1.0
  scoped_model: ^2.0.0
  flutter_markdown: 0.7.7+1
  logger: ^2.6.2
  animate_do: 4.2.0
  go_router: any
  after_layout: 1.2.0
  hive_ce: any
  flutter_smart_dialog: 4.9.8+9
  json_annotation: 4.9.0
  flutter_svg: any
  fast_immutable_collections: ^11.1.0
  extended_nested_scroll_view: 6.2.1
  keyboard_actions: 4.2.0
dev_dependencies:
  json_serializable: any
  freezed: any
  build_runner: any
  hive_ce_generator: any
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/nav/
    - assets/icons/
    - assets/svg/
    - assets/svg/user/
    - assets/svg/cate/
    - assets/json/
    - assets/images/waimai/hb/
description: 典典的小卖部,淘客版本 qq群667186542
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.27.0'
dependency_overrides:
  flutter_lints: any
  web: ^1.1.1
  meta: ^1.17.0
  collection: ^1.19.1
  flex_color_scheme:
    git:
      url: https://github.com/mdddj/flex_color_scheme
      ref: master-ohos

  loading_more_list_fast:
    git:
      url: https://github.com/mdddj/loading_more_list
  loading_more_list_library_fast:
    git:
      url: https://github.com/mdddj/loading_more_list_library
  connectivity_plus_ohos:
    git:
      url: "https://gitee.com/lewiswsq2211/connectivity_plus_ohos.git"
  path_provider:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/path_provider/path_provider
  path: 1.9.0